version: 2

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    
    steps:
      - checkout
      - setup_remote_docker
      
      - run:
          name: build image
          command: |
            docker build -t norrkin/pluralsight-docker-ci .

      - run:
          name: push image
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push norrkin/pluralsight-docker-ci

